---
- apt:
    state: latest
    name: "{{ item }}"
  with_items:
    - openssh-client
  when: openssh_client
  tags:
    - install
    - openssh

- apt:
    state: latest
    name: "{{ item }}"
  with_items:
    - openssh-server
  when: openssh_server
  tags:
    - install
    - openssh
